name: AutoGarden 🌿

on:
  schedule:
    # 3 sesi: pagi (06), siang (14), malam (22)
    - cron: '0 6,14,22 * * *'
  workflow_dispatch:

jobs:
  cultivate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Gardening Loop
        run: |
          git config --global user.name "satriazoid"
          git config --global user.email "satriaalfa77@gmail.com"

          git fetch origin main
          git reset --hard origin/main

          export TZ="Asia/Jakarta"

          # Tentukan sesi berdasarkan jam
          HOUR=$(date +%H)

          if [ "$HOUR" -lt 12 ]; then
            SESSION="🌅 Morning Session"
          elif [ "$HOUR" -lt 18 ]; then
            SESSION="☀️ Afternoon Session"
          else
            SESSION="🌙 Night Session"
          fi

          # Loop hanya 5 commit per sesi
          for i in {1..5}
          do
            sleep 1

            echo "Garden watered at: $(date) - $SESSION" > garden_log.txt
            
            git add garden_log.txt
            git commit --allow-empty -m "leaf: $SESSION $i/5 💧"
          done

          git push origin main --force
